/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AdminMonitorRouteImport } from './routes/admin/monitor'
import { Route as AdminLobbyRouteImport } from './routes/admin/lobby'
import { Route as AdminExamsRouteImport } from './routes/admin/exams'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConfigureRouteImport } from './routes/admin/configure'
import { Route as AdminHistoryIndexRouteImport } from './routes/admin/history/index'
import { Route as AdminHistorySessionIdRouteImport } from './routes/admin/history/$sessionId'
import { Route as AdminHistoryAttemptAttemptIdRouteImport } from './routes/admin/history/attempt/$attemptId'

const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitorRoute = AdminMonitorRouteImport.update({
  id: '/admin/monitor',
  path: '/admin/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLobbyRoute = AdminLobbyRouteImport.update({
  id: '/admin/lobby',
  path: '/admin/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/admin/exams',
  path: '/admin/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigureRoute = AdminConfigureRouteImport.update({
  id: '/admin/configure',
  path: '/admin/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryIndexRoute = AdminHistoryIndexRouteImport.update({
  id: '/admin/history/',
  path: '/admin/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistorySessionIdRoute = AdminHistorySessionIdRouteImport.update({
  id: '/admin/history/$sessionId',
  path: '/admin/history/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryAttemptAttemptIdRoute =
  AdminHistoryAttemptAttemptIdRouteImport.update({
    id: '/admin/history/attempt/$attemptId',
    path: '/admin/history/attempt/$attemptId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/submitted': typeof SubmittedRoute
  '/admin/configure': typeof AdminConfigureRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/lobby': typeof AdminLobbyRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/history/$sessionId': typeof AdminHistorySessionIdRoute
  '/admin/history/': typeof AdminHistoryIndexRoute
  '/admin/history/attempt/$attemptId': typeof AdminHistoryAttemptAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/submitted': typeof SubmittedRoute
  '/admin/configure': typeof AdminConfigureRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/lobby': typeof AdminLobbyRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/history/$sessionId': typeof AdminHistorySessionIdRoute
  '/admin/history': typeof AdminHistoryIndexRoute
  '/admin/history/attempt/$attemptId': typeof AdminHistoryAttemptAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/submitted': typeof SubmittedRoute
  '/admin/configure': typeof AdminConfigureRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/lobby': typeof AdminLobbyRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/history/$sessionId': typeof AdminHistorySessionIdRoute
  '/admin/history/': typeof AdminHistoryIndexRoute
  '/admin/history/attempt/$attemptId': typeof AdminHistoryAttemptAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam'
    | '/submitted'
    | '/admin/configure'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/lobby'
    | '/admin/monitor'
    | '/admin/setup'
    | '/admin/students'
    | '/admin/'
    | '/admin/history/$sessionId'
    | '/admin/history/'
    | '/admin/history/attempt/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam'
    | '/submitted'
    | '/admin/configure'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/lobby'
    | '/admin/monitor'
    | '/admin/setup'
    | '/admin/students'
    | '/admin'
    | '/admin/history/$sessionId'
    | '/admin/history'
    | '/admin/history/attempt/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/exam'
    | '/submitted'
    | '/admin/configure'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/lobby'
    | '/admin/monitor'
    | '/admin/setup'
    | '/admin/students'
    | '/admin/'
    | '/admin/history/$sessionId'
    | '/admin/history/'
    | '/admin/history/attempt/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamRoute: typeof ExamRoute
  SubmittedRoute: typeof SubmittedRoute
  AdminConfigureRoute: typeof AdminConfigureRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminLobbyRoute: typeof AdminLobbyRoute
  AdminMonitorRoute: typeof AdminMonitorRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminHistorySessionIdRoute: typeof AdminHistorySessionIdRoute
  AdminHistoryIndexRoute: typeof AdminHistoryIndexRoute
  AdminHistoryAttemptAttemptIdRoute: typeof AdminHistoryAttemptAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitor': {
      id: '/admin/monitor'
      path: '/admin/monitor'
      fullPath: '/admin/monitor'
      preLoaderRoute: typeof AdminMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lobby': {
      id: '/admin/lobby'
      path: '/admin/lobby'
      fullPath: '/admin/lobby'
      preLoaderRoute: typeof AdminLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configure': {
      id: '/admin/configure'
      path: '/admin/configure'
      fullPath: '/admin/configure'
      preLoaderRoute: typeof AdminConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/history/': {
      id: '/admin/history/'
      path: '/admin/history'
      fullPath: '/admin/history/'
      preLoaderRoute: typeof AdminHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/history/$sessionId': {
      id: '/admin/history/$sessionId'
      path: '/admin/history/$sessionId'
      fullPath: '/admin/history/$sessionId'
      preLoaderRoute: typeof AdminHistorySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/history/attempt/$attemptId': {
      id: '/admin/history/attempt/$attemptId'
      path: '/admin/history/attempt/$attemptId'
      fullPath: '/admin/history/attempt/$attemptId'
      preLoaderRoute: typeof AdminHistoryAttemptAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamRoute: ExamRoute,
  SubmittedRoute: SubmittedRoute,
  AdminConfigureRoute: AdminConfigureRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminLobbyRoute: AdminLobbyRoute,
  AdminMonitorRoute: AdminMonitorRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminHistorySessionIdRoute: AdminHistorySessionIdRoute,
  AdminHistoryIndexRoute: AdminHistoryIndexRoute,
  AdminHistoryAttemptAttemptIdRoute: AdminHistoryAttemptAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
